on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    environment: prd
    
    steps:
    - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: stop service
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "systemctl stop lbdb.service && exit"
    - name: clone repo
      continue-on-error: true
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && if [ ! -d directory ]; then git clone ${{ secrets.REPO_URL }} bot fi && exit"
    - name: connect and pull
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }}/bot && git restore . && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && exit"
    - name: replace config variables
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sh ${{ secrets.WORK_DIR }}/bot/variabilise.sh ${{ secrets.DISCORD_BOT_TOKEN }} ${{ secrets.DISCORD_SERVER_ID }} ${{ secrets.DB_HOST }} ${{ secrets.DB_PORT }} ${{ secrets.DB_USER }} ${{ secrets.DB_PASSWORD }} ${{ secrets.DB_NAME }} ${{ secrets.WORK_DIR }}/bot/config.json && exit"
    - name: maven package
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }}/bot && mvn package && exit"
    - name: start service
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "systemctl start lbdb.service && exit"
    - name: cleanup
      run: rm -rf ~/.ssh


#java -cp "/opt/lbdb/bot/target/epgp-discord-bot-0.0.1-jar-with-dependencies.jar:/opt/lbdb/bot/vendor/JDA.jar" com.epgpbot.transport.discord.DiscordBotLauncher /opt/lbdb/bot/config.json
