on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    environment: prd
    
    steps:
    - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: clone repo
      continue-on-error: true
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && if [ ! -d directory ]; then git clone ${{ secrets.REPO_URL }} bot fi && exit"
    - name: connect and pull
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }}/bot && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && exit"
    - name: debug
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 'jq --arg DISCORD_BOT_TOKEN "${{ secrets.DISCORD_BOT_TOKEN }}" --arg DISCORD_SERVER_ID "${{ secrets.DISCORD_SERVER_ID }}" ".discord_bot_token = ($DISCORD_BOT_TOKEN) | .discord_server_id = ($DISCORD_SERVER_ID)" ${{ secrets.WORK_DIR }}/bot/config.json' > ~/test.txt && exit"
    - name: replace config variables
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "jq --arg DISCORD_BOT_TOKEN "${{ secrets.DISCORD_BOT_TOKEN }}" --arg DISCORD_SERVER_ID "${{ secrets.DISCORD_SERVER_ID }}" '.discord_bot_token = ($DISCORD_BOT_TOKEN) | .discord_server_id = ($DISCORD_SERVER_ID)' ${{ secrets.WORK_DIR }}/bot/config.json && exit"
    - name: cleanup
      run: rm -rf ~/.ssh
